name: Rust CI
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Linter
      run: cargo clippy -- -D warnings
    
    - name: Format style
      run: cargo fmt --all -- --check
      
    - name: Build
      run: cargo build --verbose
      
    - name: Tests
      run: cargo test --verbose
      
      # Coverage
    - uses: actions/checkout@v1
      
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --no-fail-fast
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
        RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'

    - uses: actions-rs/grcov@v0.1

    - name: Codecov report
      uses: codecov/codecov-action@v1.0.13
      with:
        file: ${{ steps.coverage.outputs.report }}
