name: Rust

on: pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run clippy linter
      run: cargo clippy -- -D warnings
      
    - name: Run format style
      run: cargo fmt --all -- --check
      
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
